### ISSUE TITLE
Can't figure out how to embed image. 

### ISSUE THREAD

**Issue by Shy** [myConsciousness/bluesky-post#1]
Hi there 👋🏾

I'm trying to figure out how to include an image with this action. Do you have any suggestions?

**Comment by myConsciousness** [comment]
Hi @Shy !

This Action does not support uploading images or setting facets of detail, but could be implemented if there is a demand for it :) The way I envisioned using it would be to upload and post the image internally with this action, given the file path as an argument.

**Comment by Shy** [comment]
I actually tried to implement that on my own by forking your repo. I've never used dart though so I'm struggling with it a little bit. I'm sure I'll figure it out soon enough. 😅

**Comment by myConsciousness** [comment]
@Shy ,

I'll also try to implement it, but if you try to create PR, following code helps you :)

https://github.com/myConsciousness/bluesky-apod-bot/blob/6fd5ab3f34efa45d4fb5be8bbb65981aef965b32/bin/bluesky_apod_bot.dart#L172

**Comment by myConsciousness** [comment]
Hi @Shy ,

Sorry for late reply, but I released the latest build of this action, now you can upload your image with text :)

```yml
name: Send Bluesky Post

on:
    [push]

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      # You must checkout resources
      - uses: actions/checkout@v3

      - uses: myConsciousness/bluesky-post@v3
        with:
          text: "Hello, Bluesky!"
          media: cool_photo.png
          media-alt: "This is a cool photo!"
          identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
          password: ${{ secrets.BLUESKY_PASSWORD }}
```
